package rules.patient;

import code.dp.drools.cdss.model.Patient;

rule "PAGE1-01:局域治疗"
    salience 100
    no-loop
    when
        $p:Patient(cT memberOf "T1,T2,T3", cN memberOf "N0,N1", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage2(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见局域治疗（BINV-2）");
end

rule "PAGE1-02:考虑术前全身治疗"
    salience 100
    no-loop
    when
        $p: Patient(cT == "T0", cN == "N1", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage11(true);
        $p.setToPage15(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见可手术疾病的术前全身治疗（BINV-11）或参见无法手术的或局部晚期疾病（非炎性）的术前全身治疗：检查（BINV-15）");
end

rule "PAGE1-03:考虑术前全身治疗"
    salience 100
    no-loop
    when
        $p: Patient(cT == "T1", cN == "N1", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage11(true);
        $p.setToPage15(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见可手术疾病的术前全身治疗（BINV-11）或参见无法手术的或局部晚期疾病（非炎性）的术前全身治疗：检查（BINV-15）");
end

rule "PAGE1-04:考虑术前全身治疗"
    salience 100
    no-loop
    when
       $p: Patient(cT == "T2", cN == "N0", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage11(true);
        $p.setToPage15(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见可手术疾病的术前全身治疗（BINV-11）或参见无法手术的或局部晚期疾病（非炎性）的术前全身治疗：检查（BINV-15）");
end

rule "PAGE1-05:考虑术前全身治疗"
    salience 100
    no-loop
    when
        $p: Patient(cT == "T2", cN == "N1", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage11(true);
        $p.setToPage15(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见可手术疾病的术前全身治疗（BINV-11）或参见无法手术的或局部晚期疾病（非炎性）的术前全身治疗：检查（BINV-15）");
end

rule "PAGE1-06:考虑术前全身治疗"
    salience 100
    no-loop
    when
        $p: Patient(cT == "T3", cN == "N0", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage11(true);
        $p.setToPage15(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见可手术疾病的术前全身治疗（BINV-11）或参见无法手术的或局部晚期疾病（非炎性）的术前全身治疗：检查（BINV-15）");
end

rule "PAGE1-07:考虑术前全身治疗"
    salience 100
    no-loop
    when
        $p: Patient(cT == "T3", cN == "N0", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage11(true);
        $p.setToPage15(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见可手术疾病的术前全身治疗（BINV-11）或参见无法手术的或局部晚期疾病（非炎性）的术前全身治疗：检查（BINV-15）");
end

rule "PAGE1-08:考虑术前全身治疗"
    salience 100
    no-loop
    when
        $p: Patient(cT == "T3", cN == "N1", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage11(true);
        $p.setToPage15(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见可手术疾病的术前全身治疗（BINV-11）或参见无法手术的或局部晚期疾病（非炎性）的术前全身治疗：检查（BINV-15）");
end

rule "PAGE1-09:考虑术前全身治疗"
    salience 100
    no-loop
    when
        $p: Patient(cT memberOf "T0,T1,T2,T3", cN == "N2", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage11(true);
        $p.setToPage15(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见可手术疾病的术前全身治疗（BINV-11）或参见无法手术的或局部晚期疾病（非炎性）的术前全身治疗：检查（BINV-15）");
end

rule "PAGE1-10:考虑术前全身治疗"
    salience 100
    no-loop
    when
        $p: Patient(cT == "T4", cN memberOf "N0,N1,N2", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage11(true);
        $p.setToPage15(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见可手术疾病的术前全身治疗（BINV-11）或参见无法手术的或局部晚期疾病（非炎性）的术前全身治疗：检查（BINV-15）");
end

rule "PAGE1-11:考虑术前全身治疗"
    salience 100
    no-loop
    when
        $p: Patient(cT memberOf "T0,T1,T2,T3,T4,Tis", cN == "N3", cM == "M0")
    then
        System.out.println("Fact: " + drools.getFactHandle($p).getObject().toString());
        $p.setToPage11(true);
        $p.setToPage15(true);
        update($p);
        System.out.println("rule_name: " + drools.getRule().getName() + " ,result: BINV-1 -> 参见可手术疾病的术前全身治疗（BINV-11）或参见无法手术的或局部晚期疾病（非炎性）的术前全身治疗：检查（BINV-15）");
end