package rules.patient;

import code.dp.drools.cdss.model.Patient
import code.dp.drools.cdss.model.Treatment
import java.util.HashSet
import java.util.List
import java.util.ArrayList;

rule "局域治疗(BINV1-01)"
    salience 100
    no-loop
    when
        Patient(cT =="T1", cN == "N0", cM == "M0")
        or Patient(cT =="T0", cN == "N1", cM == "M0")
        or Patient(cT =="T1", cN == "N1", cM == "M0")
        or Patient(cT =="T2", cN == "N0", cM == "M0")
        or Patient(cT =="T2", cN == "N1", cM == "M0")
        or Patient(cT =="T3", cN == "N0", cM == "M0")
        or Patient(cT =="T3", cN == "N1", cM == "M0")
        $p: Patient()
    then
        $p.setToPage2(true);
        update($p);
        String result = "参见局域治疗(BINV-2)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "考虑术前全身治疗(BINV1-02)"
    salience 100
    no-loop
    when
        Patient(cT =="T0", cN == "N1", cM == "M0")
        or Patient(cT =="T1", cN == "N1", cM == "M0")
        or Patient(cT =="T2", cN == "N0", cM == "M0")
        or Patient(cT =="T2", cN == "N1", cM == "M0")
        or Patient(cT =="T3", cN == "N0", cM == "M0")
        or Patient(cT =="T3", cN == "N1", cM == "M0")
        or Patient(cT =="T0", cN == "N2", cM == "M0")
        or Patient(cT =="T1", cN == "N2", cM == "M0")
        or Patient(cT =="T2", cN == "N2", cM == "M0")
        or Patient(cT =="T3", cN == "N2", cM == "M0")
        or Patient(cT =="T4", cN == "N0", cM == "M0")
        or Patient(cT =="T4", cN == "N1", cM == "M0")
        or Patient(cT =="T4", cN == "N2", cM == "M0")
        or Patient(cT =="T0", cN == "N3", cM == "M0")
        or Patient(cT =="T0", cN == "N3", cM == "M0")
        or Patient(cT =="T1", cN == "N3", cM == "M0")
        or Patient(cT =="T2", cN == "N3", cM == "M0")
        or Patient(cT =="T3", cN == "N3", cM == "M0")
        or Patient(cT =="T4", cN == "N3", cM == "M0")
        or Patient(cT =="Tis", cN == "N3", cM == "M0")
        $p: Patient()
    then
        $p.setToPage11(true);
        update($p);
        String result = "参见可手术疾病的术前全身治疗(BINV-11)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "考虑术前全身治疗(BINV1-03)"
    salience 100
    no-loop
    when
        Patient(cT =="T0", cN == "N1", cM == "M0")
        or Patient(cT =="T1", cN == "N1", cM == "M0")
        or Patient(cT =="T2", cN == "N0", cM == "M0")
        or Patient(cT =="T2", cN == "N1", cM == "M0")
        or Patient(cT =="T3", cN == "N0", cM == "M0")
        or Patient(cT =="T3", cN == "N1", cM == "M0")
        or Patient(cT =="T0", cN == "N2", cM == "M0")
        or Patient(cT =="T1", cN == "N2", cM == "M0")
        or Patient(cT =="T2", cN == "N2", cM == "M0")
        or Patient(cT =="T3", cN == "N2", cM == "M0")
        or Patient(cT =="T4", cN == "N0", cM == "M0")
        or Patient(cT =="T4", cN == "N1", cM == "M0")
        or Patient(cT =="T4", cN == "N2", cM == "M0")
        or Patient(cT =="T0", cN == "N3", cM == "M0")
        or Patient(cT =="T0", cN == "N3", cM == "M0")
        or Patient(cT =="T1", cN == "N3", cM == "M0")
        or Patient(cT =="T2", cN == "N3", cM == "M0")
        or Patient(cT =="T3", cN == "N3", cM == "M0")
        or Patient(cT =="T4", cN == "N3", cM == "M0")
        or Patient(cT =="Tis", cN == "N3", cM == "M0")
        $p: Patient()
    then
        $p.setToPage15(true);
        update($p);
        String result = "参见无法手术的或局部晚期疾病(非炎性)的术前全身治疗：检查(BINV-15)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "T1-3,N0-1,M0疾病的局域治疗(BINV2-01)"
    salience 99
    no-loop
    when
        Patient(surgeryName=="乳房肿瘤切除术并外科腋窝分期(1类)", positiveAxillaryLymphNodes>=4, negativeAxillaryLymph==false, toPage2==true)
        $p: Patient()
    then
        $p.setToPage4(true);
        update($p);
        String result = "全乳放疗伴或不伴瘤床(1类)、锁骨下区、锁骨上区、内乳淋巴结及腋窝床的任何危及部位(1类)推量照射。如果有化疗指征，放疗通常在化疗后进行。(参见BINV-4)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "T1-3,N0-1,M0疾病的局域治疗(BINV2-02)"
    salience 99
    no-loop
    when
        Patient(surgeryName=="乳房肿瘤切除术并外科腋窝分期(1类)", positiveAxillaryLymphNodes>0, positiveAxillaryLymphNodes<3, negativeAxillaryLymph==false, toPage2==true)
        $p: Patient()
    then
        $p.setToPage4(true);
        update($p);
        String result = "全乳放疗伴或不伴瘤床(1类)推量照射。积极考虑对锁骨下区、锁骨上区、内乳淋巴结及腋窝床的任何危及部位放疗。如果有化疗指征，放疗通常在化疗后进行。(参见BINV-4)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "T1-3,N0-1,M0疾病的局域治疗(BINV2-03)"
    salience 99
    no-loop
    when
        Patient(surgeryName=="乳房肿瘤切除术并腋窝外科分期(1类)", positiveAxillaryLymphNodes==0, negativeAxillaryLymph==true, toPage2==true)
        $p: Patient()
    then
        $p.setToPage4(true);
        update($p);
        String result = "全乳放疗伴或不伴瘤床(1类)推量照射。并考虑对肿瘤位于中央/内侧或是肿瘤>2cm且伴有其他高危特征(年轻或广泛淋巴脉管浸润[LVI])的患者行区域淋巴放疗。或考虑对部分低危患者行加速部分乳房照射(APBI)。如果有化疗指征，放疗通常在化疗后进行。(参见BINV-4)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "T1-3,N0-1,M0疾病的局域治疗(BINV2-04)"
    salience 99
    no-loop
    when
        Patient(surgeryName=="全乳切除并外科腋窝分期(1类)±乳房重建", toPage2==true)
        $p: Patient()
    then
        $p.setToPage3(true);
        update($p);
        String result = "参见“区域治疗”(BINV-3)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "T1-3,N0-1,M0疾病的局域治疗(BINV2-05)"
    salience 99
    no-loop
    when
        Patient(cT == "T2")
        or Patient(cT == "T3")
        Patient(toPage2==true, surgeryName=="保乳治疗", conserveStandard==true, cancerSize < 5)
        $p: Patient()
    then
        $p.setToPage11(true);
        update($p);
        String result = "考虑术前全身治疗指南。(BINV-11)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗(BINV4-01)"
    salience 97
    no-loop
    when
        Patient(toPage4==true, histologyType == "导管癌", er==1, pr==0, her2==1)
        or Patient(toPage4==true, histologyType == "小叶癌", er==1, pr==0, her2==1)
        or Patient(toPage4==true, histologyType == "混合性癌", er==1,pr==0, her2==1)
        or Patient(toPage4==true, histologyType == "化生性癌", er==1,pr==0, her2==1)
        or Patient(toPage4==true, histologyType == "导管癌", er==0, pr==1, her2==1)
        or Patient(toPage4==true, histologyType == "小叶癌", er==0, pr==1, her2==1)
        or Patient(toPage4==true, histologyType == "混合性癌", er==0, pr==1, her2==1)
        or Patient(toPage4==true, histologyType == "化生性癌", er==0, pr==1, her2==1)
        or Patient(toPage4==true, histologyType == "导管癌", er==1, pr==1, her2==1)
        or Patient(toPage4==true, histologyType == "小叶癌", er==1, pr==1, her2==1)
        or Patient(toPage4==true, histologyType == "混合性癌", er==1, pr==1, her2==1)
        or Patient(toPage4==true, histologyType == "化生性癌", er==1, pr==1, her2==1)
        $p: Patient()
    then
        $p.setToPage5(true);
        update($p);
        String result = "参见全身辅助治疗：激素受体阳性-HER2阳性疾病(BINV-5)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗(BINV4-02)"
    salience 97
    no-loop
    when
        Patient(toPage4==true, histologyType == "导管癌", er==1, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "小叶癌", er==1, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "混合性癌", er==1, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "化生性癌", er==1, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "导管癌", er==0, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "小叶癌", er==0, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "混合性癌", er==0, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "化生性癌", er==0, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "导管癌", er==1, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "小叶癌", er==1, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "混合性癌", er==1, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "化生性癌", er==1, pr==1, her2==0)
        $p: Patient()
    then
        $p.setToPage6(true);
        update($p);
        String result = "参见全身辅助治疗： 淋巴结阴性-激素受体阳性-HER2阴性疾病(BINV-6)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗(BINV4-03)"
    salience 97
    no-loop
    when
        Patient(toPage4==true, histologyType == "导管癌", er==1, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "小叶癌", er==1, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "混合性癌", er==1, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "化生性癌", er==1, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "导管癌", er==0, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "小叶癌", er==0, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "混合性癌", er==0, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "化生性癌", er==0, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "导管癌", er==1, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "小叶癌", er==1, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "混合性癌", er==1, pr==1, her2==0)
        or Patient(toPage4==true, histologyType == "化生性癌", er==1, pr==1, her2==0)
        $p: Patient()
    then
        $p.setToPage7(true);
        update($p);
        String result = "参见全身辅助治疗： 淋巴结阳性-激素受体阳性-HER2阴性疾病(BINV-7)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗(BINV4-04)"
    salience 97
    no-loop
    when
        $p: Patient()
        Patient(toPage4==true, histologyType == "导管癌", er==0, pr==0, her2==1)
        or Patient(toPage4==true, histologyType == "小叶癌", er==0, pr==0, her2==1)
        or Patient(toPage4==true, histologyType == "混合性癌", er==0, pr==0, her2==1)
        or Patient(toPage4==true, histologyType == "化生性癌", er==0, pr==0, her2==1)
    then
        $p.setToPage8(true);
        update($p);
        String result = "参见全身辅助治疗： 激素受体阴性-HER2阳性疾病(BINV-8)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗(BINV4-05)"
    salience 97
    no-loop
    when
        Patient(toPage4==true, histologyType == "导管癌", er==0, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "小叶癌", er==0, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "混合性癌", er==0, pr==0, her2==0)
        or Patient(toPage4==true, histologyType == "化生性癌", er==0, pr==0, her2==0)
        $p: Patient()
    then
        $p.setToPage9(true);
        update($p);
        String result = "参见全身辅助治疗：激素受体阴性-HER2阴性疾病(BINV-9)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗(BINV4-06)"
    salience 97
    no-loop
    when
        Patient(toPage4==true, histologyType == "小管癌", er==1, pr==1)
        or Patient(toPage4==true, histologyType == "黏液癌", er==1, pr==1)
        or Patient(toPage4==true, histologyType == "小管癌", er==1, pr==0)
        or Patient(toPage4==true, histologyType == "黏液癌", er==1, pr==0)
        or Patient(toPage4==true, histologyType == "小管癌", er==0, pr==1)
        or Patient(toPage4==true, histologyType == "黏液癌", er==0, pr==1)
        or Patient(toPage4==true, histologyType == "小管癌", er==0, pr==0)
        or Patient(toPage4==true, histologyType == "黏液癌", er==0, pr==0)
        $p: Patient()
    then
        $p.setToPage10(true);
        update($p);
        String result = "参见全身辅助治疗： 表现良好的组织学类型(BINV-10)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗：激素受体阴性-HER2阳性疾病(BINV8-01)"
    salience 93
    no-loop
    when
        Patient(toPage8==true, histologyType == "导管癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        $p: Patient()
    then
        $p.setToPage18(true);
        update($p);
        String result = "考虑辅助化疗并曲妥珠单抗(2B类)(BINV-18)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗：激素受体阴性-HER2阳性疾病(BINV8-02)"
    salience 93
    no-loop
    when
        Patient(toPage8==true, histologyType == "导管癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=0.5)
        $p: Patient()
    then
        $p.setToPage18(true);
        update($p);
        String result = "考虑辅助辅助化疗并曲妥珠单抗(BINV-17)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗：激素受体阴性-HER2阳性疾病(BINV8-03)"
    salience 93
    no-loop
    when
        Patient(toPage8==true, histologyType == "导管癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        $p: Patient()
    then
        $p.setToPage18(true);
        update($p);
        String result = "考虑辅助辅助化疗并曲妥珠单抗(BINV-17)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗：激素受体阴性-HER2阳性疾病(BINV8-04)"
    salience 93
    no-loop
    when
        Patient(toPage8==true, histologyType == "导管癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize<=1.0, primaryTumorSize > 0.6)
        $p: Patient()
    then
        $p.setToPage18(true);
        update($p);
        String result = "考虑辅助辅助化疗并曲妥珠单抗(BINV-17)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗：激素受体阴性-HER2阳性疾病(BINV8-05)"
    salience 93
    no-loop
    when
        Patient(toPage8==true, histologyType == "导管癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT1", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT2", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT3", pN=="pN0", lymphaticMetastasis==0, primaryTumorSize>1.0)
        $p: Patient()
    then
        $p.setToPage18(true);
        update($p);
        String result = "考虑辅助辅助化疗并曲妥珠单抗(1类)(BINV-17)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗：激素受体阴性-HER2阳性疾病(BINV8-06)"
    salience 93
    no-loop
    when
        Patient(toPage8==true, histologyType == "导管癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "导管癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "小叶癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "混合性癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT1", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT2", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        or Patient(toPage8==true, histologyType == "化生性癌", pT == "pT3", pN=="pN1mi", lymphaticMetastasis==0, primaryTumorSize>1.0)
        $p: Patient()
    then
        $p.setToPage18(true);
        update($p);
        String result = "考虑辅助辅助化疗并曲妥珠单抗(1类)(BINV-17)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "全身辅助治疗：激素受体阴性-HER2阳性疾病(BINV8-07)"
    salience 93
    no-loop
    when
        Patient(histologyType == "导管癌", lymphaticMetastasis > 0, toPage8 == true)
        or Patient(histologyType == "小叶癌", lymphaticMetastasis > 0, toPage8 == true)
        or Patient(histologyType == "混合性癌", lymphaticMetastasis > 0, toPage8 == true)
        or Patient(histologyType == "化生性癌", lymphaticMetastasis > 0, toPage8 == true)
        $p: Patient()
    then
        $p.setToPage18(true);
        update($p);
        String result = "辅助化疗并曲妥珠单抗(1类) 或 内分泌治疗或辅助化疗并曲妥珠单抗+帕妥珠单抗(BINV-17)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病(BINV18-01)"
    salience 83
    no-loop
    when
        Patient(clinicalStage == "复发", toPage18 == true)
        or Patient(histologyType == "IV期", toPage18 == true)
        $p: Patient()
    then
        $p.setToPage19(true);
        update($p);
        String result = "参见“局部和区域复发的治疗”(BINV-19)和支持治疗";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病(BINV18-02)"
    salience 83
    no-loop
    when
        Patient(clinicalStage == "复发", toPage18 == true)
        or Patient(histologyType == "IV期", toPage18 == true)
        $p: Patient()
    then
        $p.setToPage20(true);
        update($p);
        String result = "参见“复发或IV期(M1)疾病的全身治疗”(BINV-20)和支持治疗";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-01)"
    salience 81
    no-loop
    when
        $p: Patient(metastaticSites == "骨转移", toPage20 == true)
    then
        String result = "加用地诺单抗、唑来勝酸或帕米膦酸";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-02)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==1, pr==1, her2==0)
    then
        $p.setToPage21(true);
        update($p);
        String result = "参见BINV-21";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-03)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==1, pr==0, her2==0)
    then
        $p.setToPage21(true);
        update($p);
        String result = "参见BINV-21";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-04)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==0, pr==1, her2==0)
    then
        $p.setToPage21(true);
        update($p);
        String result = "参见BINV-21";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-05)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==1, pr==1, her2==1, treatedOfThePastYear == true)
    then
        $p.setToPage23(true);
        update($p);
        String result = "参见BINV-23";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-06)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==1, pr==0, her2==1, treatedOfThePastYear == true)
    then
        $p.setToPage23(true);
        update($p);
        String result = "参见BINV-23";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-07)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==0, pr==1, her2==1, treatedOfThePastYear == true)
    then
        $p.setToPage23(true);
        update($p);
        String result = "参见BINV-23";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-08)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==1, pr==1, her2==1, treatedOfThePastYear == false)
    then
        $p.setToPage24(true);
        update($p);
        String result = "参见BINV-24";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-09)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==1, pr==0, her2==1, treatedOfThePastYear == false)
    then
        $p.setToPage24(true);
        update($p);
        String result = "参见BINV-24";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-10)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==0, pr==1, her2==1, treatedOfThePastYear == false)
    then
        $p.setToPage24(true);
        update($p);
        String result = "参见BINV-24";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-11)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==0, pr==0, her2==1)
    then
        $p.setToPage26(true);
        update($p);
        String result = "参见BINV-26";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-12)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==0, pr==1, her2==1)
    then
        $p.setToPage26(true);
        update($p);
        String result = "参见BINV-26";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-13)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==1, pr==0, her2==1)
    then
        $p.setToPage26(true);
        update($p);
        String result = "参见BINV-26";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-14)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==0, pr==0, her2==0)
    then
        $p.setToPage27(true);
        update($p);
        String result = "参见BINV-27";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-15)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==0, pr==1, her2==0)
    then
        $p.setToPage27(true);
        update($p);
        String result = "参见BINV-27";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV20-16)"
    salience 81
    no-loop
    when
        $p: Patient(toPage20 == true, er==1, pr==0, her2==0)
    then
        $p.setToPage27(true);
        update($p);
        String result = "参见BINV-27";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV26-01)"
    salience 75
    no-loop
    when
        Patient(toPage26 == true, thirdLineStatus == 1, thirdLineTreatEvaluation == "疾病进展")
        or Patient(toPage26 == true, thirdLineStatus == 1, ecogPerformanceStatus >=3)
        $p: Patient()
    then
        //排除 : 一线已用方案、二线已用方案、三线已用方案
        HashSet<String> treatment = new HashSet<>();
        treatment.add("支持治疗");
        treatment.add("曲妥珠单抗+拉帕替尼");
        treatment.remove($p.getFrontLineTreatUsed());
        treatment.remove($p.getSecondLineTreatUsed());
        treatment.remove($p.getThirdLineTreatUsed());
        $p.setTreatmentName(treatment);
        String result = $p.getTreatmentName().toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV26-02)"
    salience 75
    no-loop
    when
        Patient(toPage26 == true, thirdLineStatus == 0, secondLineStatus == 1, secondLineTreatEvaluation == "疾病进展")
        or Patient(toPage26 == true, thirdLineStatus == 0, secondLineStatus == 1, secondLineToxicityOfTolerance == "无法耐受")
        $p: Patient()
    then
        //TODO 排除 : 一线已用方案、二线已用方案
        HashSet<String> treatment = new HashSet<>();
        treatment.add("帕妥珠单抗+曲妥珠单抗+多西他赛");
        treatment.add("帕妥珠单抗+曲妥珠单抗+紫杉醇");
        treatment.add("曲妥珠单抗+美坦新偶联物(T-DM1)");
        treatment.add("曲妥珠单抗+紫杉醇");
        treatment.add("曲妥珠单抗+紫杉醇+卡铂");
        treatment.add("曲妥珠单抗+多西他赛");
        treatment.add("曲妥珠单抗+长春瑞滨");
        treatment.add("曲妥珠单抗+卡培他滨");
        treatment.add("拉帕替尼+卡培他演");
        treatment.add("曲妥珠单抗+拉帕替尼");
        treatment.add("曲妥珠单抗+帕妥珠单抗+紫杉醇");
        treatment.add("曲妥珠单抗+帕妥珠单抗+卡培他滨");
        treatment.add("曲妥珠单抗+帕妥珠单抗+吉西他滨");
        treatment.add("曲妥珠单抗+帕妥珠单抗+长春瑞滨");
        treatment.add("曲妥珠单抗+帕妥珠单抗+艾日布林");
        treatment.add("曲妥珠单抗+帕妥珠单抗+奥拉帕利");
        treatment.add("曲妥珠单抗+帕妥珠单抗+他拉唑帕利");
        treatment.add("曲妥珠单抗+帕妥珠单抗+环磷酰胺");
        treatment.add("曲妥珠单抗+帕妥珠单抗+卡铂");
        treatment.add("曲妥珠单抗+帕妥珠单抗+白蛋白结合紫杉醇");
        treatment.add("曲妥珠单抗+帕妥珠单抗+顺铂");
        treatment.add("曲妥珠单抗+帕妥珠单抗+表阿霉素");
        treatment.add("曲妥珠单抗+帕妥珠单抗+伊沙匹隆");
        treatment.add("曲妥珠单抗+伊沙匹隆");
        treatment.add("曲妥珠单抗+表阿霉素");
        treatment.add("曲妥珠单抗+顺铂");
        treatment.add("曲妥珠单抗+白蛋白结合紫杉醇");
        treatment.add("曲妥珠单抗+卡铂");
        treatment.add("曲妥珠单抗+环磷酰胺");
        treatment.add("曲妥珠单抗+艾日布林");
        treatment.add("曲妥珠单抗+吉西他滨");
        treatment.remove($p.getFrontLineTreatUsed());
        $p.setTreatmentName(treatment);
        String result = $p.getTreatmentName().toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV26-03)"
    salience 75
    no-loop
    when
        Patient(toPage26 == true, thirdLineStatus == 0, secondLineStatus == 0, frontLineStatus == 1, frontLineTreatEvaluation == "疾病进展")
        or Patient(toPage26 == true, thirdLineStatus == 0, secondLineStatus == 0, frontLineStatus == 1, frontLineToxicityOfTolerance == "无法耐受")
        $p: Patient()
    then
        HashSet<String> treatment = new HashSet<>();
        treatment.add("帕妥珠单抗+曲妥珠单抗+多西他赛");
        treatment.add("帕妥珠单抗+曲妥珠单抗+紫杉醇");
        treatment.add("曲妥珠单抗+美坦新偶联物(T-DM1)");
        treatment.add("曲妥珠单抗+紫杉醇");
        treatment.add("曲妥珠单抗+紫杉醇+卡铂");
        treatment.add("曲妥珠单抗+多西他赛");
        treatment.add("曲妥珠单抗+长春瑞滨");
        treatment.add("曲妥珠单抗+卡培他滨");
        treatment.add("拉帕替尼+卡培他演");
        treatment.add("曲妥珠单抗+拉帕替尼");
        treatment.add("曲妥珠单抗+帕妥珠单抗+紫杉醇");
        treatment.add("曲妥珠单抗+帕妥珠单抗+卡培他滨");
        treatment.add("曲妥珠单抗+帕妥珠单抗+吉西他滨");
        treatment.add("曲妥珠单抗+帕妥珠单抗+长春瑞滨");
        treatment.add("曲妥珠单抗+帕妥珠单抗+艾日布林");
        treatment.add("曲妥珠单抗+帕妥珠单抗+奥拉帕利");
        treatment.add("曲妥珠单抗+帕妥珠单抗+他拉唑帕利");
        treatment.add("曲妥珠单抗+帕妥珠单抗+环磷酰胺");
        treatment.add("曲妥珠单抗+帕妥珠单抗+卡铂");
        treatment.add("曲妥珠单抗+帕妥珠单抗+白蛋白结合紫杉醇");
        treatment.add("曲妥珠单抗+帕妥珠单抗+顺铂");
        treatment.add("曲妥珠单抗+帕妥珠单抗+表阿霉素");
        treatment.add("曲妥珠单抗+帕妥珠单抗+伊沙匹隆");
        treatment.add("曲妥珠单抗+伊沙匹隆");
        treatment.add("曲妥珠单抗+表阿霉素");
        treatment.add("曲妥珠单抗+顺铂");
        treatment.add("曲妥珠单抗+白蛋白结合紫杉醇");
        treatment.add("曲妥珠单抗+卡铂");
        treatment.add("曲妥珠单抗+环磷酰胺");
        treatment.add("曲妥珠单抗+艾日布林");
        treatment.add("曲妥珠单抗+吉西他滨");
        treatment.remove($p.getFrontLineTreatUsed());
        treatment.remove($p.getSecondLineTreatUsed());
        $p.setTreatmentName(treatment);
        String result = $p.getTreatmentName().toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "复发或IV期(M1)疾病的全身治疗(BINV26-04)"
    salience 75
    no-loop
    when
        Patient(toPage26 == true, thirdLineStatus == 0, secondLineStatus == 0, frontLineStatus == 0)
        $p: Patient()
    then
        HashSet<String> treatment = new HashSet<>();
        treatment.add("帕妥珠单抗+曲妥珠单抗+多西他赛");
        treatment.add("帕妥珠单抗+曲妥珠单抗+紫杉醇");
        treatment.add("曲妥珠单抗+美坦新偶联物(T-DM1)");
        treatment.add("曲妥珠单抗+紫杉醇");
        treatment.add("曲妥珠单抗+紫杉醇+卡铂");
        treatment.add("曲妥珠单抗+多西他赛");
        treatment.add("曲妥珠单抗+长春瑞滨");
        treatment.add("曲妥珠单抗+卡培他滨");
        treatment.add("拉帕替尼+卡培他演");
        treatment.add("曲妥珠单抗+拉帕替尼");
        treatment.add("曲妥珠单抗+帕妥珠单抗+紫杉醇");
        treatment.add("曲妥珠单抗+帕妥珠单抗+卡培他滨");
        treatment.add("曲妥珠单抗+帕妥珠单抗+吉西他滨");
        treatment.add("曲妥珠单抗+帕妥珠单抗+长春瑞滨");
        treatment.add("曲妥珠单抗+帕妥珠单抗+艾日布林");
        treatment.add("曲妥珠单抗+帕妥珠单抗+奥拉帕利");
        treatment.add("曲妥珠单抗+帕妥珠单抗+他拉唑帕利");
        treatment.add("曲妥珠单抗+帕妥珠单抗+环磷酰胺");
        treatment.add("曲妥珠单抗+帕妥珠单抗+卡铂");
        treatment.add("曲妥珠单抗+帕妥珠单抗+白蛋白结合紫杉醇");
        treatment.add("曲妥珠单抗+帕妥珠单抗+顺铂");
        treatment.add("曲妥珠单抗+帕妥珠单抗+表阿霉素");
        treatment.add("曲妥珠单抗+帕妥珠单抗+伊沙匹隆");
        treatment.add("曲妥珠单抗+伊沙匹隆");
        treatment.add("曲妥珠单抗+表阿霉素");
        treatment.add("曲妥珠单抗+顺铂");
        treatment.add("曲妥珠单抗+白蛋白结合紫杉醇");
        treatment.add("曲妥珠单抗+卡铂");
        treatment.add("曲妥珠单抗+环磷酰胺");
        treatment.add("曲妥珠单抗+艾日布林");
        treatment.add("曲妥珠单抗+吉西他滨");
        $p.setTreatmentName(treatment);
        String result = $p.getTreatmentName().toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "可手术疾病的术前全身治疗：检查(BINV11)"
    salience 90
    no-loop
    when
        Patient(toPage11==true)
        Patient(cT=="T2",cN=="N0",cM=="M0")
        or Patient(cT=="T2",cN=="N1",cM=="M0")
        or Patient(cT=="T3",cN=="N0",cM=="M0")
        or Patient(cT=="T3",cN=="N1",cM=="M0")
        (Patient(conserveStandard==true)
        or Patient(positive2NegativeBeforeSurgery==true,positiveAxillaryLymphNodesBeforeSurgery>0))
        $p: Patient()
    then
        $p.setToPage12(true);
        update($p);
        String result = "参见\"术前全身治疗：乳腺和腋窝评估\"(BINV-12)";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：乳腺和腋窝评估(BINV12-01)"
    salience 89
    no-loop
    when
        Patient(toPage12==true, clinicalAxillaryLymphNode==1)
        $p: Patient()
    then
        HashSet<String> treatment = new HashSet<>();
        treatment.add("腋窝淋巴结活检");
        $p.setTreatmentName(treatment);
        String result = $p.getTreatmentName().toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：乳腺和腋窝评估(BINV12-02)"
    salience 89
    no-loop
    when
        Patient(toPage12==true, axillaryLymphNodePunctureResults==0)
        $p: Patient()
    then
        $p.setToPage13(true);
        update($p);
        HashSet<String> treatment = new HashSet<>();
        treatment.add("前哨淋巴结活检(SLNB)首选在术前全身治疗后进行");
        $p.setTreatmentName(treatment);
        String result = $p.getTreatmentName().toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：乳腺和腋窝评估(BINV12-03)"
    salience 89
    no-loop
    when
        Patient(toPage12==true, axillaryLymphNodePunctureResults==1)
        $p: Patient()
    then
        HashSet<String> treatment = new HashSet<>();
        treatment.add("术前全身治疗后行腋窝再分期");
        $p.setTreatmentName(treatment);
        String result = $p.getTreatmentName().toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：乳腺和腋窝评估(BINV12-04)"
    salience 89
    no-loop
    when
        Patient(toPage12==true, clinicalAxillaryLymphNodesAfterNeoadjuvantChemotherapy==1)
        $p: Patient()
    then
        $p.setToPage13(true);
        update($p);
        HashSet<String> treatment = new HashSet<>();
        treatment.add("行腋窝淋巴结清扫(ALND)");
        $p.setTreatmentName(treatment);
        String result = $p.getTreatmentName().toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：乳腺和腋窝评估(BINV12-05)"
    salience 89
    no-loop
    when
        Patient(toPage12==true, clinicalAxillaryLymphNodesAfterNeoadjuvantChemotherapy==0,resultsOfAxillaryLymphNodePunctureAfterNeoadjuvantChemotherapy==0)
        $p: Patient()
    then
        $p.setToPage13(true);
        update($p);
        HashSet<String> treatment = new HashSet<>();
        treatment.add("前哨淋巴结活检(SLNB)");
        $p.setTreatmentName(treatment);
        String result = $p.getTreatmentName().toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：乳腺和腋窝评估(BINV12-06)"
    salience 89
    no-loop
    when
        Patient(toPage12==true, clinicalAxillaryLymphNodesAfterNeoadjuvantChemotherapy==0,resultsOfAxillaryLymphNodePunctureAfterNeoadjuvantChemotherapy==1)
        $p: Patient()
    then
        $p.setToPage13(true);
        update($p);
        HashSet<String> treatment = new HashSet<>();
        treatment.add("腋窝淋巴结清扫");
        $p.setTreatmentName(treatment);
        String result = $p.getTreatmentName().toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：手术治疗(BINV13-01)"
    salience 88
    no-loop
    when
        Patient(toPage13==true, systemicTherapyStatus=="在任何时候经证实的进展性疾病")
        or Patient(toPage13==true, systemicTherapyStatus=="部分缓解，乳房肿瘤切除术不可行")
        $p: Patient()
    then
        $p.setToPage14(true);
        update($p);
        String result = "参见”乳房切除术“（BINV-14）";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：手术治疗(BINV13-02)"
    salience 88
    no-loop
    when
        Patient(toPage13==true, systemicTherapyStatus=="完全缓解")
        or Patient(toPage13==true, systemicTherapyStatus=="部分缓解，乳房肿瘤切除术可行")
        $p: Patient()
    then
        $p.setToPage14(true);
        update($p);
        String result = "参见”乳房肿瘤切除术“（BINV-14）";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：手术治疗(BINV13-03)"
    salience 88
    no-loop
    when
        Patient(toPage13==true, considerPreoperativeSystemicTreatment==true)
        $p: Patient()
    then
        $p.setToPageK(true);
        update($p);
end

rule "术前全身治疗：辅助治疗(BINV14-01)"
    salience 87
    no-loop
    when
        (Patient(surgeryName=="乳房切除") or Patient(toPage14==true, surgeryName=="乳房切除并外科腋窝分期+乳房重建")
            or Patient(toPage14==true, surgeryName=="乳房肿瘤切除并外科腋窝分期"))
        Patient(toPage4==true,surgicalAxillaryStaging=="前哨淋巴结活检")
        or (Patient(toPage4==true,surgicalAxillaryStaging=="I级腋窝淋巴结清扫")
            or Patient(toPage4==true,surgicalAxillaryStaging=="I级、II级腋窝淋巴结清扫")
            or Patient(toPage4==true,surgicalAxillaryStaging=="I级、II级、III级腋窝淋巴结清扫"))
        Patient(toPage4==true, beforeSurgeryStatus==false)
        $p: Patient()
    then
        $p.setToPageJ(true);
        update($p);
        String result = "完成术前既定化疗方案";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：辅助治疗(BINV14-02)"
    salience 87
    no-loop
    when
        Patient(toPage14==true,er==0,pr==0,her2==0)
        (Patient(surgeryName=="乳房切除") or Patient(surgeryName=="乳房切除并外科腋窝分期+乳房重建") or Patient(surgeryName=="乳房肿瘤切除并外科腋窝分期"))
        (Patient(surgicalAxillaryStaging=="前哨淋巴结活检") or Patient(surgicalAxillaryStaging=="I级腋窝淋巴结清扫")
            or Patient(surgicalAxillaryStaging=="I级、II级腋窝淋巴结清扫") or Patient(surgicalAxillaryStaging=="I级、II级、III级腋窝淋巴结清扫"))
        (Patient(preoperativeChemotherapy=="紫杉烷类") or Patient(preoperativeChemotherapy=="烷化剂类") or Patient(preoperativeChemotherapy=="蒽环类"))
        $p: Patient()
    then
        $p.setToPageK(true);
        update($p);
        String result = "卡培他滨";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：辅助治疗(BINV14-03)"
    salience 87
    no-loop
    when
        Patient(surgeryName=="乳房切除") or Patient(surgeryName=="乳房肿瘤切除")
        Patient(toPage14==true,cN=="N1",ypN=="N0")
        $p: Patient()
    then
        String result = "胸壁+锁骨下区+锁骨上区、内乳淋巴结及腋窝床的任何危及部位放疗";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：辅助治疗(BINV14-04)"
    salience 87
    no-loop
    when
        Patient(surgeryName=="乳房切除") or Patient(surgeryName=="乳房肿瘤切除")
        Patient(toPage14==true,preoperativeAdjuvantTreatmentOfAxillaryLymphNodes==1)
        $p: Patient()
    then
        String result = "胸壁+锁骨下区+锁骨上区、内乳淋巴结及腋窝床的任何危及部位放疗";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前全身治疗：辅助治疗(BINV14-05)"
    salience 87
    no-loop
    when
        Patient(toPage14==true)
        (Patient(er==1,pr==0) or Patient(er==0,pr==1) or Patient(er==1,pr==1))
        (Patient(surgeryName=="乳房切除") or Patient(surgeryName=="全乳切除并外科腋窝分期(1类)±乳房重建") or Patient(surgeryName=="乳房肿瘤切除并外科腋窝分期"))
        (Patient(surgicalAxillaryStaging=="前哨淋巴结活检") or Patient(surgicalAxillaryStaging=="I级腋窝淋巴结清扫")
            or Patient(surgicalAxillaryStaging=="I级、II级腋窝淋巴结清扫") or Patient(surgicalAxillaryStaging=="I级、II级、III级腋窝淋巴结清扫"))
        $p: Patient()
    then
        $p.setToPageJ(true);
        update($p);
end

rule "术前全身治疗：辅助治疗(BINV14-06)"
    salience 87
    no-loop
    when
        Patient(toPage14==true,her2==1)
        (Patient(surgeryName=="乳房切除") or Patient(surgeryName=="乳房切除并外科腋窝分期+乳房重建") or Patient(surgeryName=="乳房肿瘤切除并外科腋窝分期"))
        (Patient(surgicalAxillaryStaging=="前哨淋巴结活检") or Patient(surgicalAxillaryStaging=="I级腋窝淋巴结清扫")
            or Patient(surgicalAxillaryStaging=="I级、II级腋窝淋巴结清扫") or Patient(surgicalAxillaryStaging=="I级、II级、III级腋窝淋巴结清扫"))
        $p: Patient()
    then
        $p.setToPageK(true);
        update($p);
        String result = "曲妥珠单抗or帕妥珠单抗or曲妥珠单抗+帕妥珠单抗,计划=‘靶向治疗+放疗+内分泌治疗’";
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "辅助内分泌治疗(BINVJ-01)"
    salience 50
    no-loop
    when
        Patient(toPageJ==true,menstrualStatus==0)
        $p: Patient()
    then
        $p.setToPageK(true);
        String result = "他莫昔芬治疗5年or他莫昔芬治疗5年+卵巢抑制or他莫昔芬治疗5年+卵巢切除or芳香化酶抑制剂治疗5年+卵巢抑制or芳香化酶抑制剂治疗5年+卵巢切除";
        $p.setEndocrinotherapy1(result);
        update($p);
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "辅助内分泌治疗(BINVJ-02)"
    salience 50
    no-loop
    when
        Patient(toPageJ==true,menstrualStatus==0,endocrinotherapy1 == "他莫昔芬治疗5年or他莫昔芬治疗5年+卵巢抑制or他莫昔芬治疗5年+卵巢切除or芳香化酶抑制剂治疗5年+卵巢抑制or芳香化酶抑制剂治疗5年+卵巢切除")
        $p: Patient()
    then
        $p.setToPageK(true);
        String result = "他莫昔芬治疗5年or不进一步内分泌治疗";
        $p.setEndocrinotherapy2(result);
        update($p);
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "辅助内分泌治疗(BINVJ-03)"
    salience 50
    no-loop
    when
        Patient(toPageJ==true,menstrualStatus==1,endocrinotherapy1 == "他莫昔芬治疗5年or他莫昔芬治疗5年+卵巢抑制or他莫昔芬治疗5年+卵巢切除or芳香化酶抑制剂治疗5年+卵巢抑制or芳香化酶抑制剂治疗5年+卵巢切除")
        $p: Patient()
    then
        $p.setToPageK(true);
        String result = "芳香化酶抑制剂治疗5年or他莫昔芬治疗5年";
        $p.setEndocrinotherapy2(result);
        update($p);
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "辅助内分泌治疗(BINVJ-04)"
    salience 50
    no-loop
    when
        Patient(toPageJ==true,menstrualStatus==1)
        $p: Patient()
    then
        HashSet<String> treatment = new HashSet<>();
        treatment.add("第一周期内分泌治疗=‘他莫昔芬治疗2-3年’and (第二周期内分泌治疗=‘芳香化酶抑制剂，内分泌治疗共5年’or‘芳香化酶抑制剂治疗至多5年’）");
        treatment.add("第一周期内分泌治疗=‘芳香化酶抑制剂治疗5年’and 第二周期内分泌治疗=‘芳香化酶抑制剂5年’");
        treatment.add("第一周期内分泌治疗=‘芳香化酶抑制剂治疗2-3年’and 第二周期内分泌治疗=‘他莫昔芬，内分泌治疗共5年’");
        treatment.add("第一周期内分泌治疗=‘芳香化酶抑制剂治疗4.5-6年’and（第二周期内分泌治疗=‘他莫昔芬治疗5年’or‘芳香化酶抑制剂治疗5年’）");
        String result = treatment.toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "辅助内分泌治疗(BINVJ-05)"
    salience 50
    no-loop
    when
        Patient(toPageJ==true,menstrualStatus==1)
        Patient(taboos=="芳香化酶抑制剂禁忌症") or Patient(taboos=="拒绝接受芳香化酶抑制剂治疗") or Patient(taboos=="无法耐受芳香化酶抑制剂治疗")
        $p: Patient()
    then
        HashSet<String> treatment = new HashSet<>();
        treatment.add("他莫昔芬治疗5年");
        treatment.add("他莫昔芬治疗至多10年");
        String result = treatment.toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前/辅助治疗方案(BINVK-01)"
    salience 49
    no-loop
    when
        Patient(toPageK==true,her2==0)
        $p: Patient()
    then
        HashSet<String> treatment = new HashSet<>();
        treatment.add("剂量密集AC（阿霉素+环磷酰胺）序贯紫杉醇");
        treatment.add("TC（多西他赛和环磷酰胺）");
        treatment.add("剂量密集AC（阿霉素/环磷酰胺）");
        treatment.add("AC（阿霉素/环磷酰胺）");
        treatment.add("CMF（环磷酰胺/甲氨蝶呤/氟尿嘧啶）");
        treatment.add("AC（阿霉素/环磷酰胺）序贯紫杉醇");
        treatment.add("AC（阿霉素/环磷酰胺）序贯多西他赛");
        treatment.add("EC（表阿霉素/环磷酰胺）");
        treatment.add("TAC（多西他赛/阿霉素/环磷酰胺）");
        String result = treatment.toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end

rule "术前/辅助治疗方案(BINVK-02)"
    salience 49
    no-loop
    when
        Patient(toPageK==true,her2==1)
        $p: Patient()
    then
        HashSet<String> treatment = new HashSet<>();
        treatment.add("AC（阿霉素/环磷酰胺）序贯T（多西他赛）+H（曲妥珠单抗）");
        treatment.add("AC（阿霉素/环磷酰胺）序贯T（多西他赛）+H（曲妥珠单抗）+帕妥珠单抗");
        treatment.add("紫杉醇+曲妥珠单抗");
        treatment.add("TC（多西他赛/卡铂）+H（曲妥珠单抗）");
        treatment.add("TC（多西他赛/卡铂）+H（曲妥珠单抗）+帕妥珠单抗");
        treatment.add("多西他赛+环磷酰胺+曲妥珠单抗");
        treatment.add("AC（阿霉素/环磷酰胺）序贯T（多西他赛）+H（曲妥珠单抗）");
        treatment.add("AC（阿霉素/环磷酰胺）序贯T（多西他赛）+H（曲妥珠单抗）+帕妥珠单抗");
        String result = treatment.toString();
        System.out.println(drools.getRule().getName() + " ==> " + result);
end